Repository damnever/pigar, pull requests merged in 2022-11, with the labels that each got.

#97 Fixed too many values to unpack error in `parse_git_config`
  pigar/helpers.py
  pigar/tests/fake_git_conf/config
  pigar/tests/test_helpers.py
Labels: size/S

#117 Ignore ipynb magics and shell commands
  pigar/parser.py
  pigar/tests/imports_example/notebook.ipynb
Labels: size/M

#115 Parse requirements file with the more sophisticated utility
  pigar/core.py
  pigar/helpers.py
  pigar/tests/fake_reqs.txt
  pigar/tests/fake_reqs_2.txt
  pigar/tests/test_helpers.py
  py2_requirements.txt
  py3_requirements.txt
Labels: size/L

#121 Bump version: 1.0.1
  CHANGELOG.md
  pigar/version.py
Labels: size/S

#122 Version 1.0.2: fix requirements
  CHANGELOG.md
  pigar/version.py
  setup.py
Labels: size/S
